
###
//find all the todos
GET http://localhost:3001/todos


###
// create new todo
POST http://localhost:3001/todo/new HTTP/1.1
Content-Type: application/json

{
  "text":"This is random text1."
}


###
//complete toggle
PUT http://localhost:3001/todo/complete/626529d8013fe20fc21301a9


###
//delete todo
DELETE http://localhost:3001/todo/delete/62652e2f0c845e92f3aef658
